tailwind.config.js

어떤 변경 사항이 있나요?
closed #1 
daisyUI 테마를 변경했습니다.

Design: 테마 변경

---

src/components/common/Drawer.tsx
src/components/common/Header.tsx
src/components/common/Layout.tsx
src/store/test.ts

어떤 변경 사항이 있나요?
closed #4 
헤더 UI 초안 작성하였습니다.
|로그인 상태|사이드바|
| ---- | ---- |
|![스크린샷 2024-04-28 152705](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/3b8d1e8b-211b-42dd-8c27-7d077cdd97e5)|![스크린샷 2024-04-28 152647](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/f56666b8-4dbc-4333-8b78-44bb17a88977)|

Design : header 컴포넌트 디자인

---

src/App.tsx
src/components/common/Layout.tsx
src/components/common/Profile.tsx
src/router.tsx
src/routes/MyPage.tsx

- 마이페이지 레이아웃 작성
어떤 변경 사항이 있나요?
closed #5 
마이페이지 레이아웃을 작성했습니다.
헤더를 불포함하기 때문에 라우터 중첩을 변경하고, Layout 컴포넌트의 margin을 수정했습니다.

Design: 마이페이지 레이아웃 작성

---

.gitignore
src/components/socialLogin/KakaoLoginButton.tsx
src/components/socialLogin/KakaoRedirection.tsx
src/constants.ts
src/mocks/handlers.ts
src/router.tsx
src/service/socialLogin/useSendCodeMutation.ts

어떤 변경 사항이 있나요?
closed #12 
소셜 로그인 인가코드를 받아왔고 msw로 모킹해서 액세스토큰을 받아오는 것을 확인했습니다.

Feat/kakao 카카오 소셜 로그인 인가코드 받아오기

---

src/components/common/EmailAuthModal.tsx
src/mocks/handlers.ts
src/routes/SignUp.tsx
src/service/signup/useAuthEmailMutation.ts

어떤 변경 사항이 있나요?
이메일 인증코드 입력창 모달을 만들었습니다.
아직 초안이고 자릿수가 정해져있다면 otp형식으로 하고 카운트다운도 추가 할 예정입니다.

Feat/emailauth 이메일 인증코드 입력창 제작

---

src/components/common/Profile.tsx
src/mocks/handlers.ts
src/router.tsx
src/routes/MyPage.tsx
src/routes/ProfileUpdate.tsx
src/store/api.tsx
src/types/interface.ts

어떤 변경 사항이 있나요?
closed #11 
마이페이지에서 정보를 불러오기 전에 렌더링되는 오류를 수정했습니다.
회원 정보 수정 페이지 레이아웃을 작성했습니다.
회원 정보 수정 기능을 구현했습니다.

Feat: 회원 정보 수정 페이지 작성

---

src/components/common/Profile.tsx
src/router.tsx
src/routes/MyPage.tsx
src/routes/Shop.tsx

어떤 변경 사항이 있나요?
closed #16 
판매자 정보 페이지 레이아웃을 구현했습니다.

Design: 판매자 정보 페이지 레이아웃 작성

---

index.html
package-lock.json
package.json
src/router.tsx
src/routes/PostCreate.tsx
src/routes/PostEdit.tsx
src/types/interface.ts
tsconfig.json

어떤 변경 사항이 있나요?
closed #18 
게시글 등록/수정 페이지 레이아웃 작성했습니다.
지도 불러오기 및 지도 움직이기 기능 구현했습니다.
게시글 상세 페이지 레이아웃 작성 후 수정 페이지 데이터 연결 예정입니다.
(현재 수정 페이지 레이아웃 등록 페이지와 동일!!)

Design: 게시글 등록/수정 페이지 레이아웃 작성

---

src/components/common/Header.tsx
src/components/home/HomeList.tsx
src/components/home/HomeMap.tsx
src/components/home/MyLocationMarker.tsx
src/components/home/ProductMarkers.tsx
src/index.css
src/mocks/handlers.ts
src/routes/Home.tsx
src/store/atom.ts

어떤 변경 사항이 있나요?
closed #25 
- 지도에서 클러스터나 마커 클릭 시 해당 정보를 리스트에 띄워주도록 했습니다.
- 현재 클릭을 해야만 리스트가 올라오기 때문에 처음 홈에 들어갔을 때 리스트에 아무 것도 뜨지 않고 있습니다.
- 위치 정보 동의 여부에 따라 처음에도 띄울 수 있도록 진행 중에 있습니다.
- 아직 최종은 아니고 백엔드와 연동 후에 추가 될 부분들이 많다는 점 알아주시면 감사하겠습니다.

Feat: 홈 화면 리스트 업데이트

---

src/components/common/Header.tsx
src/components/common/Profile.tsx
src/mocks/handlers.ts
src/router.tsx
src/routes/MyPage.tsx
src/routes/PointCharge.tsx
src/store/api.tsx
src/types/interface.ts

어떤 변경 사항이 있나요?
closed #24 
- 포인트 충전 페이지 레이아웃을 작성했습니다.
- 마이페이지 충전 버튼과 연결했습니다.
- Header 컴포넌트의 css를 조금 수정했습니다.
- Profile 컴포넌트 변경사항이 왜 저렇게 나타나는지는 잘 모르겠지만 jsx상 변경은 이 두가지가 다입니다.
- isLoading 조건부 렌더링 제거
- 하단 badge 조건부 렌더링 수정
- badge db 테이블을 분리했기 때문에 badge 조회 기능 추가했습니다.
- h2 태그보다 h1 태그가 적합한 것 같아 수정했습니다.

Design: 포인트 충전 페이지 레이아웃 작성

---

.eslintrc.cjs
src/components/common/CardListItem.tsx
src/components/common/CardListPage.tsx
src/components/common/RatingModal.tsx
src/index.css
src/mocks/handlers.ts
src/mocks/purchaseHistoryData.ts
src/router.tsx
src/routes/MyPage.tsx
src/routes/PurchaseHistory.tsx
src/service/mypage/usePurchaseHistoryQuery.ts
src/service/mypage/useSendReviewMutation.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
closed #30 
- 판매내역, 찜 내역에서 그대로 사용 될 공통 컴포넌트들이라 양이 좀 많은 점 양해 부탁드립니다 ..!
- mypage파일 변경사항 보시면 클래스 순서만 바뀐거 보이실텐데 vs코드 익스텐션에서 Headwind 설치 해주시면 좋을 것 같습니다. ( 저장하면 클래스 순서 정렬해주는 기능입니다. 저는 처음부터 깔려있었는데 까먹고 말씀을 못드렸습니다 ..!)
- ++ 폰트 변경했습니다. 슬랙에서 보시고 폰트 변경 원하시면 말씀해주세요.
|구매 내역|후기 모달|후기 등록 후|
| :---: | :---: | :---: |
|![image](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/195cc1f9-e28c-44bc-bab7-e61f32ac0d75)| ![image](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/e0969656-b323-40e6-bd19-b7d8ed8b0bdb) | ![image](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/e66ec791-1643-4b15-8d67-f02dd8c6df9d) |

Feat: 구매 내역 페이지 및 별점 모달 창

---

src/components/common/PointCalc.tsx
src/mocks/handlers.ts
src/router.tsx
src/routes/MyPage.tsx
src/routes/PointCharge.tsx
src/routes/PostCreate.tsx
src/routes/PostDetail.tsx
src/routes/PostEdit.tsx
src/routes/ProfileUpdate.tsx
src/routes/SignUp.tsx
src/routes/Transfer.tsx
src/store/api.tsx
src/types/interface.ts

어떤 변경 사항이 있나요?
closed #28 
회원 탈퇴 기능을 구현했습니다. (새로운 이슈로 만들었어야 했는데 실수했어요😭)
포인트 충전 페이지와 계좌 송금 페이지 구성이 비슷하여 충전 페이지 리팩토링해서 공용 컴포넌트로 만들었습니다.
회원가입 페이지랑 회원 정보 수정 페이지 오타 발견해서 수정했습니다.

Design: 계좌 송금 페이지 레이아웃 작성

---

src/components/common/Layout.tsx
src/components/header/Header.tsx
src/components/header/SearchBar.tsx
src/components/home/HomeMap.tsx
src/components/home/ProductMarkers.tsx
src/mocks/data/searchData.ts
src/mocks/handlers.ts
src/service/map/useAllProductQuery.ts
src/service/map/useSearchResultQuery.ts
src/store/atom.ts

어떤 변경 사항이 있나요?
- common폴더에 있던 header컴포넌트를 빼고 따로 header관련 폴더를 만들었습니다.
- 검색을 하면 검색 결과가 리스트에 뜨고 검색 결과에 맞는 클러스터러만 남게 됩니다.
- 검색 초기화 버튼을 눌러 다시 모든 상품을 조회 할 수 있습니다.

Feat: 검색 및 검색 결과 지도 연동

---

src/components/common/NotFoundPage.tsx
src/router.tsx

어떤 변경 사항이 있나요?
- 에러 페이지를 생성했습니다. 기본적으로 저희가 만든 적 없는 경로로 이동 할 경우 나오게 했고 작업하시다가 따로 에러 처리가 필요하신 부분에 NotFoundPage 컴포넌트를 추가 하시면 될 것 같습니다.
- UI 수정 원하시면 말씀 해주세요
| 에러페이지 | 
| :---: |
| ![image](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/0bc6cb91-e6ca-4398-92dd-3f1126df9ceb) |

Feat: 에러페이지

---

src/components/common/EmailAuthModal.tsx
src/mocks/handlers.ts
src/routes/SignUp.tsx
src/service/signup/useAuthEmailMutation.ts
src/service/signup/useConfirmEmailAuth.ts
src/service/signup/useEmailAuthReqestMutation.ts
src/service/signup/useSignupMutation.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
- 회원가입,이메일 인증 핸들러 작성
- 유효성 검사를 통과하지 못하면 회원가입이 불가능 하게 했습니다.
- 이메일 인증을 통과하지 못하면 회원가입이 불가능 하게 했습니다.
- 프로필 이미지를 추가해 폼데이터로 제출하도록 변경했습니다. 기본 이미지로 다시 제출 가능합니다.
- 전화번호 정규식을 - 포함하도록 변경했습니다.
| 기본 이미지 | 이미지 선택 | 요청 결과 |
| :---: | :---: | :---: | 
| ![스크린샷 2024-05-14 222208](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/e87d5532-086b-4e77-a232-3489f3379b30) | ![스크린샷 2024-05-14 222158](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/73ecae90-4344-4c9b-a14c-dcc989cfe2fa) | ![image](https://github.com/2024TeamUnity/Goods_FE/assets/111565040/3b6683a4-02fe-4e09-b9a1-fc92f58ee8bc) |

Feat: 회원가입,이메일 인증 추가 구현

---

src/components/profile/PasswordModal.tsx
src/mocks/handlers.ts
src/routes/ProfileUpdate.tsx
src/service/mypage/useUpdatePasswordMutation.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
closed #51 
- 회원 정보 수정 페이지에 비밀번호 변경/간편결제 비밀번호 변경 버튼을 만들어 모달로 구현했습니다. (api 분리 이슈로...)
- 프로필 이미지 타입에 따라 전송되는 필드를 분리했습니다.

Feat: 회원 정보 수정 페이지 수정

---

package-lock.json
package.json
src/routes/Shop.tsx
tsconfig.json

```
npm i --save-dev @types/node
```
어떤 변경 사항이 있나요?
빌드 오류나는 부분들 수정 했습니다.

Fix: 빌드 오류 해결

---

.github/workflows/deploy.yml
build.sh

어떤 변경 사항이 있나요?
- release 브랜치에 머지 될 때 마다 제 개인 레포지토리로 자동으로 push되도록 설정했습니다. ( 나중에 main으로 변경 예정)
- 그 후 vercel에서 자동으로 배포 됩니다.

Chore: 자동 배포 Github Actions 작성

---

src/components/postImg/PostImgList.tsx
src/components/postMap/PostMap.tsx
src/routes/PostCreate.tsx
src/routes/PostEdit.tsx
src/store/atom.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
closed #61 
- 백엔드 분들의 요구에 따라 게시글 등록/수정시 거래희망장소 지번주소를 같이 보냅니다.
- 백엔드 분들과 상의해 게시글 등록/수정시 서버로 보낼 데이터를 변경했습니다.
- 게시글 수정시 기존 사진들 중 삭제된 사진의 url을 보내달라셔서 삭제되지 않은 url들을 보내는 것에서 삭제된 url들을 보내는 것으로 로직을 수정했습니다.
- 코드가 길어져 게시글 작성/수정 페이지에서 지도 컴포넌트를 분리했습니다.

Feat: 거래 희망 장소 지번 주소로 변환

---

.github/workflows/deploy.yml
vercel.json

어떤 변경 사항이 있나요?
- Vercel에 재배포하고 Github Actions 수정했습니다.

Chore: 재배포 및 Github Actions 수정

---

src/components/socialLogin/KakaoRedirection.tsx
src/service/signin/useSigninMutation.ts
src/service/signin/useSignoutMutation.ts
src/util/authAxios.ts

어떤 변경 사항이 있나요?
- 이메일 로그인, 소셜 로그인 모두 토큰 재발급 원할하게 동작하도록 보완했습니다.
- 작업 하시는데 불편하실 것 같아서 우선 이 기능만 먼저 올립니다.

Fix: 로그인 토큰 재발급

---

index.html
package-lock.json
package.json
src/components/chatroom/ChatHistory.tsx
src/components/chatroom/ChatInput.tsx
src/components/chatroom/GoodsInfo.tsx
src/components/common/Drawer.tsx
src/components/common/FindPasswordModal.tsx
src/components/header/SearchBar.tsx
src/components/home/HomeMap.tsx
src/router.tsx
src/routes/ChatRoom.tsx
src/routes/ChatRoomList.tsx
src/routes/PostDetail.tsx
src/service/chat/useChatHistoryQuery.ts
src/service/map/useSearchMutation.ts
src/store/atom.ts
src/types/interface.ts
src/util/authAxios.ts
vite.config.ts

```
npm i @types/sockjs-client
npm i @stomp/stompjs
```
어떤 변경 사항이 있나요?
- 검색 기능 연동했습니다.
- 채팅 말풍선 방향이 안맞는 이슈가 있습니다 ㅠ 조금 더 생각해보겠습니다

Feat: 채팅,검색 연동

---

src/components/chatroom/ChatHistory.tsx
src/components/chatroom/GoodsInfo.tsx
src/components/common/CardListItem.tsx
src/components/common/CardListPage.tsx
src/components/common/PointCalc.tsx
src/components/postImg/PostImgList.tsx
src/components/profile/PasswordModal.tsx
src/main.tsx
src/routes/ChatRoom.tsx
src/routes/MyPage.tsx
src/routes/Payment.tsx
src/routes/PostDetail.tsx
src/routes/ProfileUpdate.tsx
src/service/map/useSearchMutation.ts
src/service/mypage/useSendReviewMutation.ts
src/service/mypage/useUpdatePasswordMutation.ts
src/service/mypage/useUserQueries.ts
src/service/point/useTradePointMutation.ts
src/service/post/useReadPostQuery.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
- 채팅방에 시간과 말풍선 위치가 잘못 뜨는 오류를 수정했습니다.
- 채팅방 CSS를 일부 수정했습니다.
- 구매목록 페이지에선 uploaded_before가 아니라 traded_before로 데이터를 주고받도록 백엔드 분들과 맞춰 필드명을 수정했습니다.
- 포인트 거래 오류를 수정했습니다.
- 필드명 수정
- 포인트 잔액 계산 수정
- 기존에 등록한 간편결제 비밀번호가 없는 경우 현재 비밀번호 입력칸을 입력하지 않아도 되도록 기능 추가했습니다.
- 후기 등록 api 백엔드 연동했습니다.

Fix: 채팅방 UI 오류 수정

---

src/components/charge/ChargeBtn.tsx
src/components/chatroom/GoodsInfo.tsx
src/components/common/LoadingSpinner.tsx
src/components/common/PointCalc.tsx
src/routes/ChatRoomList.tsx
src/routes/PostDetail.tsx
src/routes/PostEdit.tsx
src/routes/ProfileUpdate.tsx
src/routes/PurchaseHistory.tsx
src/routes/SalesHistory.tsx
src/routes/SignIn.tsx
src/routes/WishHistory.tsx

어떤 변경 사항이 있나요?
- useQuery로 데이터를 받아 온 후의 로딩 상태를 로딩 컴포넌트로 변경했습니다.
- 혹시 적용 안 된 페이지 있으면 말씀 해 주시면 감사하겠습니다.

Design: 로딩컴포넌트 적용

---

.eslintrc.cjs
package-lock.json
package.json
src/components/chatroom/GoodsInfo.tsx
src/components/common/CardListItem.tsx
src/components/common/HistoryPageContainer.tsx
src/components/common/Observer.tsx
src/components/common/PointCalc.tsx
src/components/common/SalesHistoryContainer.tsx
src/components/home/HomeList.tsx
src/router.tsx
src/routes/MyPage.tsx
src/routes/Payment.tsx
src/routes/PostDetail.tsx
src/routes/SalesHistory.tsx
src/routes/Shop.tsx
src/routes/WishHistory.tsx
src/service/mypage/useSalseHistoryQuery.ts
src/service/mypage/useWishHistoryQuery.ts
src/util/addComma.ts
src/util/useReduceHistory.ts
vite.config.ts

```
npm install react-intersection-observer --save
```
어떤 변경 사항이 있나요?
- 프록시 서버 주소를 변경했습니다.
- 여러 번 쓰이던 addComma함수를 유틸 폴더로 옮겼습니다.
- 관심 목록,판매 목록 페이지 리스트에 무한 스크롤 기능을 추가했습니다.
- 관심 목록, 판매 목록 페이지 컴포넌트를 새로 작성했습니다. 구매 목록도 변경 할 예정입니다.
- 메인화면 리스트를 페이지로 받으면 마커도 페이지로 바뀌어서 아직 시도하지 않았습니다. 방법을 조금 더 고민해보겠습니다.
- 구매 목록은 현재 데이터를 볼 수가 없어서 아직 시도하지 않았습니다. 뒤에 이어서 진행할 예정입니다.

Feat: 무한 스크롤

---

package-lock.json
package.json
src/components/home/HomeMap.tsx

```
npm i lodash
npm i --save lodash
```
어떤 변경 사항이 있나요?
- 지도에서 좌표가 변경 될 때 마다 서버에 요청을 보내는 드래그 이벤트 핸들러에 디바운스를 적용 했습니다.
- 메인화면 리스트 관련은 api 수정 가능성이 있어서 회의 후에 이어서 진행하겠습니다.

Feat: 지도 이동 디바운스

---

src/components/common/RatingModal.tsx
src/index.css
src/routes/ChatRoomList.tsx
src/routes/PurchaseHistory.tsx
src/service/chat/useChatRoomListQuery.ts
src/service/chat/useDeleteChatRoomMutation.ts
src/service/mypage/usePurchaseHistoryQuery.ts
src/service/mypage/useSendReviewMutation.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
- 구매목록 무한스크롤 추가했습니다.
- 채팅 목록 무한스크롤 추가했습니다.
- 채팅방 나가기 추가했습니다.
- 리뷰 작성 시 0.5점 단위로 부여 가능하게 수정했습니다.

Feat: 채팅방 무한스크롤, 채팅방 나가기

---

src/components/chatroomList/ChatRoomListItem.tsx
src/routes/ChatRoomList.tsx
src/service/chat/useChatHistoryQuery.ts
src/types/interface.ts

어떤 변경 사항이 있나요?
- 정현님 의견 반영해서 채팅방 삭제 버튼 누르면 삭제 가능한 상태로 변경되고 모달을 통해 삭제 하도록 수정했습니다.
- 현재 채팅방이 없고 만들수도 없어서 캡쳐해서 보여드릴 수가 없네요 ㅠㅠ 채팅방 무한스크롤 끝나시고 바로 pr올려주시면
캡쳐도 올리겠습니다.

Refactor: 채팅방 나가기 UI 수정

---

src/components/carousel/Carousel.tsx
src/components/chatroom/ChatHistory.tsx
src/components/common/HistoryPageContainer.tsx
src/components/home/ProductMarkers.tsx
src/components/postImg/PostImgList.tsx
src/components/profile/Star.tsx
src/routes/PostDetail.tsx
src/routes/PurchaseHistory.tsx
src/routes/SalesHistory.tsx
src/routes/SignUp.tsx
src/routes/WishHistory.tsx
src/service/map/useNearbyGoods.ts

어떤 변경 사항이 있나요?
- 배포 후 발견된 array 오류 수정했습니다
- 구매 내역, 관심 목록, 판매 내역 페이지 모바일 사이즈에서 호버시 가로 스크롤이 생기는 css 수정했습니다
- 호버 구현을 md 사이즈 이상으로 제한했습니다
- 회원가입 페이지 프로필 사진 부분에 오타가 있어서 수정했습니다

Fix: undefined 처리 수정

---

src/components/charge/ChargeBtn.tsx
src/routes/PostDetail.tsx
src/service/map/useNearbyGoods.ts
src/service/map/useSearchMutation.ts
src/util/authAxios.ts
vercel.json

어떤 변경 사항이 있나요?
- vite proxy 설정했습니다
- 메인페이지 리스트 페이지네이션 타입 에러 뜨는 것 수정했습니다. 
- 검색 기능 페이지네이션 처리 하기 전이라 에러 뜨는 부분 임시 주석처리 해놨습니다.

Fix: 배포 환경 프록시 수정

---

src/components/bottomSheet/BottomSheet.tsx
src/components/header/SearchBar.tsx
src/components/home/HomeAddr.tsx
src/components/home/HomeMap.tsx
src/components/home/ProductMarkers.tsx
src/service/map/useSearchMutation.ts

어떤 변경 사항이 있나요?
- 검색 초기화 버튼 클릭 시 해당 위치 근처 상품을 리스트에 다시 표시하도록 수정했습니다.
- 검색,위치 필터링 결과 리스트에 무한 스크롤을 적용했습니다.
- 위치 필터링 시 이동 하지 않던 문제를 해결했습니다.
- bottomSheet 닫혀있을 때 높이 수정했습니다.

Refactor: 검색 부분 리팩토링

---

src/components/common/Drawer.tsx
src/components/header/SearchBar.tsx
src/components/home/ProductMarkers.tsx
src/components/postImg/PostImgList.tsx
src/routes/ChatRoomList.tsx
src/service/chat/useChatHistoryQuery.ts
src/service/chat/useChatRoomListQuery.ts
src/service/map/useClusterInfoQuery.ts
src/service/map/useSearchMutation.ts
src/service/mypage/usePurchaseHistoryQuery.ts
src/service/mypage/useSalseHistoryQuery.ts
src/service/mypage/useWishHistoryQuery.ts

어떤 변경 사항이 있나요?
- 채팅방 목록 페이징 문제로 안 읽은 채팅 개수 총합 기능은 삭제했습니다
- 배포시 혹시 모를 array 타입 에러를 방지하기 위해 일부 코드를 수정했습니다

Refactor: 타입 가드 및 안 읽은 채팅 개수 총합 기능 삭제

---

vercel.json

어떤 변경 사항이 있나요?
- url 이동 에러 관련해서 vercel.json에 기본 라우팅 경로 추가했습니다
- vercel proxy 경로 수정했습니다

Fix: vercel proxy 수정
